### ISSUE TITLE
Thanks very much!!!!

### ISSUE THREAD

**Issue by kingtelepuz5** [haoheliu/2021-ISMIR-MSS-Challenge-CWS-PResUNet#2]
I have not tried it yet, but I have been looking for software for 3 months to separate the noise of keystrokes from my music, I recorded it on a dictaphone in nature, and this noise of impacts terribly cuts my ears, if really your software will be able to help me (I will try later when there is a stable internet for downloading repo), I will be grateful to you for a thousand years!

**Comment by haoheliu** [comment]
Thanks for your interest! If your recorded voice contains noise, maybe my vocal separation model can help. You can have a try.
