### ISSUE TITLE
分离任务遇到ImportError错误

### ISSUE THREAD

**Issue by acely** [haoheliu/2021-ISMIR-MSS-Challenge-CWS-PResUNet#5]
环境：CentOS 8.2，Anaconda3-2021.05（
Conda虚拟环境：Python3.8

安装命令：`pip3 install -r requirements.txt`

执行命令：`python3 main.py -i example/test/xuemaojiao.wav -o example/results`

遇到错误为：
```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from predictor import SubbandResUNetPredictor
  File "/root/2021-ISMIR-MSS-Challenge-CWS-PResUNet/predictor.py", line 11, in <module>
    from demucs_predictor import DemucsPredictor
  File "/root/2021-ISMIR-MSS-Challenge-CWS-PResUNet/demucs_predictor.py", line 33, in <module>
    from demucs.utils import apply_model, load_model  # noqa
ImportError: cannot import name 'apply_model' from 'demucs.utils' (/root/anaconda3/lib/python3.8/site-packages/demucs/utils.py)
```

**Comment by haoheliu** [comment]
@acely 可以看一下demucs安装的版本吗 我检查一下是不是这里有问题

**Comment by haoheliu** [comment]
OK 我在colab里复现到这个错误了。我检查一下

**Comment by haoheliu** [comment]
@acely 现在bug应该解决了 你可以再试一下

**Comment by acely** [comment]
看了下，demucs版本是3.0.1

**Comment by haoheliu** [comment]
@acely bugs fixed

**Comment by acely** [comment]
非常感谢及时回复，不过现在遇到了新问题
在`pip3 install -r requirements.txt`时报错（之前不会报错）：
```
Collecting demucs (from -r requirements.txt (line 25))
  Could not find a version that satisfies the requirement demucs (from -r requirements.txt (line 25)) (from versions: )
No matching distribution found for demucs (from -r requirements.txt (line 25))
```

我本以为是我测试时把环境搞乱了，于是把整个服务器都重装了一遍，确保环境是干净的，但还是抛出这个错误。

**Comment by haoheliu** [comment]
> 非常感谢及时回复，不过现在遇到了新问题 在`pip3 install -r requirements.txt`时报错（之前不会报错）：
> 
> ```
> Collecting demucs (from -r requirements.txt (line 25))
>   Could not find a version that satisfies the requirement demucs (from -r requirements.txt (line 25)) (from versions: )
> No matching distribution found for demucs (from -r requirements.txt (line 25))
> ```
> 
> 我本以为是我测试时把环境搞乱了，于是把整个服务器都重装了一遍，确保环境是干净的，但还是抛出这个错误。

这个错误应该和这个repo就没有关系了，应该是环境问题，可以试试pip3 install demucs==3.0.1能不能运行

**Comment by acely** [comment]
我推测可能是demucs那边在维护pip源吧，因为我试了下[https://github.com/facebookresearch/demucs/blob/main/docs/linux.md](url)提到的`python3 install -U demucs`也是不行
我打算再等等看，观察下过段时间pip是否恢复正常。

非常感谢你，另外你的voicefixer项目也很赞！

**Comment by haoheliu** [comment]
不客气 感谢关注我们的项目～
